---
name: idr0118-keenan-flylightsheet/experimentA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes

  - name: Characteristics [Developmental Stage]
    clientname: Developmental Stage
    include: yes

  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: yes

  - name: Comment [Genotype Comments]
    clientname: Genotype Comments
    include: yes

  - name: Experimental Condition [Genetic Cross]
    clientname: Genetic Cross
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier]
          clientname: Gene Identifier
          include: true
          omitempty: false
        - name: Comment [Gene Identifier]
          clientname: Gene Identifier URL
          clientvalue: >
            https://ensembl.org/Drosophila_melanogaster/Gene/Summary?g={{ value|urlencode }}
          include: true
        - name: Comment [Gene Symbol]
          clientname: Gene Symbol
          include: true
          omitempty: false

  - group:
      namespace: openmicroscopy.org/mapr/gene/supplementary
      columns:
      - name: Comment [Gene Name]
        clientname: Gene Name
        include: true
      - name: Comment [Gene Annotation Comments]
        clientname: Gene Annotation Comments
        include: true


advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
